# -*- coding: utf-8 -*-
"""
Persian Translations generator for Anytype.
"""
import json
import re

# Comprehensive direct phrase translations
PHRASE_MAP = {
    # System Types
    "Page": "برگه",
    "Pages": "برگه‌ها",
    "Task": "کار",
    "Tasks": "کارها",
    "Collection": "مجموعه",
    "Collections": "مجموعه‌ها",
    "Bookmark": "نشانک",
    "Bookmarks": "نشانک‌ها",
    "Image": "تصویر",
    "Images": "تصاویر",
    "Note": "یادداشت",
    "Notes": "یادداشت‌ها",
    "File": "فایل",
    "Files": "فایل‌ها",
    "Video": "ویدیو",
    "Videos": "ویدیوها",
    "Audio": "صدا",
    "Audios": "صداها",
    "Type": "نوع",
    "Types": "نوع‌ها",
    "Object": "شیء",
    "Objects": "اشیاء",
    "Property": "ویژگی",
    "Properties": "ویژگی‌ها",
    "Relation": "ویژگی",
    "Relations": "ویژگی‌ها",
    "Space": "فضا",
    "Spaces": "فضاها",
    "Channel": "کانال",
    "Channels": "کانال‌ها",
    "Vault": "مخزن امن",
    "Profile": "نمایه",
    "Account": "حساب کاربری",
    "Settings": "تنظیمات",
    "App Settings": "تنظیمات برنامه",
    "Channel Settings": "تنظیمات کانال",
    "Profile Settings": "تنظیمات نمایه",
    "Vault Settings": "تنظیمات مخزن امن",

    # Actions & Buttons
    "Share": "اشتراک‌گذاری",
    "Share Anytype": "اشتراک‌گذاری Anytype",
    "Save": "ذخیره",
    "Cancel": "لغو",
    "Delete": "حذف",
    "Edit": "ویرایش",
    "Add": "افزودن",
    "Create": "ایجاد",
    "Create new": "ایجاد جدید",
    "Rename": "تغییر نام",
    "Duplicate": "تکثیر",
    "Move": "انتقال",
    "Copy": "رونوشت",
    "Copy link": "رونوشت پیوند",
    "Copy URL": "رونوشت آدرس",
    "Copy text": "رونوشت متن",
    "Cut": "برش",
    "Paste": "چسباندن",
    "Undo": "واگرد",
    "Redo": "از نو",
    "Archive": "بایگانی",
    "Restore": "بازیابی",
    "Remove": "برداشتن",
    "Clear": "پاک کردن",
    "Select": "انتخاب",
    "Select all": "انتخاب همه",
    "Done": "انجام شد",
    "Close": "بستن",
    "Back": "بازگشت",
    "Next": "بعدی",
    "Continue": "ادامه",
    "Confirm": "تأیید",
    "Apply": "اعمال",
    "Reset": "بازنشانی",
    "Search": "جستجو",
    "Filter": "پالایش",
    "Sort": "مرتب‌سازی",
    "Group": "گروه‌بندی",
    "View": "نما",
    "Preview": "پیش‌نمایش",
    "Open": "باز کردن",
    "Open in new window": "باز کردن در پنجره جدید",
    "Open in new tab": "باز کردن در برگه جدید",
    "Open fullscreen": "نمایش تمام‌صفحه",
    "Download": "دانلود",
    "Upload": "بارگذاری",
    "Import": "درون‌ریزی",
    "Export": "برون‌بری",
    "Connect": "اتصال",
    "Disconnect": "قطع اتصال",
    "Sync": "همگام‌سازی",
    "Lock": "قفل کردن",
    "Unlock": "باز کردن قفل",
    "Show": "نمایش",
    "Hide": "پنهان کردن",
    "Expand": "گسترش",
    "Collapse": "جمع کردن",
    "Expand all": "گسترش همه",
    "Collapse all": "جمع کردن همه",

    # Editor Controls & Description
    "Show description": "نمایش توضیحات",
    "Hide description": "پنهان کردن توضیحات",
    "Add cover": "افزودن جلد",
    "Change cover": "تغییر جلد",
    "Remove cover": "حذف جلد",
    "Add icon": "افزودن آیکون",
    "Change icon": "تغییر آیکون",
    "Remove icon": "حذف آیکون",
    "Description": "توضیحات",
    "Add a description": "افزودن توضیحات",
    "Property description": "توضیحات ویژگی",
    "Object cover": "جلد شیء",
    "Untitled": "بدون عنوان",

    # Sidebar
    "Home and Pinned": "صفحه اصلی و سنجاق‌شده",
    "Recently edited": "اخیراً ویرایش‌شده",
    "Recently created": "اخیراً ایجاد‌شده",
    "Recently used": "اخیراً استفاده‌شده",
    "Recently opened": "اخیراً بازشده",
    "Recently active": "اخیراً فعال",
    "Recently added": "اخیراً افزوده‌شده",
    "Tree": "درختواره",
    "Tree Diagnostics": "عیب‌یابی درختواره",
    "Unread": "خوانده‌نشده",
    "Bin": "زباله‌دان",
    "My Favorites": "علاقه‌مندی‌های من",
    "Favorites": "علاقه‌مندی‌ها",
    "Move to Bin": "انتقال به زباله‌دان",
    "Restore from Bin": "بازیابی از زباله‌دان",
    "Empty Bin": "خالی کردن زباله‌دان",
    "Switch to tree view": "تغییر به نمای درختی",
    "Switch to compact view": "تغییر به نمای فشرده",
    "Switch to detailed view": "تغییر به نمای با جزئیات",

    # Layout Direction & Settings
    "Layout": "چیدمان",
    "Layout direction": "چیدمان",
    "Right to left": "از راست به چپ",
    "Left to right": "از چپ به راست",
    "Appearance": "ظاهر",
    "Theme": "پوسته",
    "Dark": "تاریک",
    "Light": "روشن",
    "System": "سیستم",
    "Font": "قلم",
    "App font": "قلم برنامه",
    "Language": "زبان",
    "Language & Region": "زبان و منطقه",
    "Spellcheck language": "زبان بررسی املا",
    "Interface Language": "زبان رابط کاربری",
    "Date & Time": "تاریخ و زمان",
    "Date format": "قالب تاریخ",
    "Time format": "قالب زمان",
    "First day of the week": "اولین روز هفته",
    "First day of week": "اولین روز هفته",

    # Status & General
    "Status": "وضعیت",
    "Synced": "همگام‌سازی شده",
    "Not Synced": "همگام‌سازی نشده",
    "Syncing": "در حال همگام‌سازی",
    "Connected": "متصل",
    "Disconnected": "قطع",
    "Connecting...": "در حال اتصال...",
    "Offline": "آفلاین",
    "Online": "آنلاین",
    "Pending": "در انتظار",
    "Rejected": "ردشده",
    "Allowed": "مجاز",
    "Denied": "ردشده",
    "Enabled": "فعال",
    "Disabled": "غیرفعال",
    "On": "روشن",
    "Off": "خاموش",
    "Default": "پیش‌فرض",
    "Custom": "سفارشی",
    "All": "همه",
    "None": "هیچ‌کدام",
    "Selected": "انتخاب‌شده",
    "All values": "همه مقادیر",
    "Any name": "هر نامی",
    "Not now": "اکنون نه",
    "No home": "بدون خانه",
    "No results": "نتیجه‌ای یافت نشد",
    "Nothing here": "چیزی اینجا نیست",
    "Empty": "خالی",
    "Loading...": "در حال بارگذاری...",
    "Please wait...": "لطفاً صبر کنید...",
    "Success": "موفقیت",
    "Error": "خطا",
    "Warning": "هشدار",
    "Info": "اطلاعات",
    "Details": "جزئیات",
    "Members": "اعضا",
    "Channel Members": "اعضای کانال",
    "Add members": "افزودن اعضا",
    "Invite": "دعوت",
    "Invite members": "دعوت اعضا",
    "Invite link": "پیوند دعوت",
    "Share invite link": "اشتراک‌گذاری پیوند دعوت",
    "Copy invite link": "رونوشت پیوند دعوت",
    "Removal history": "تاریخچه حذف",
    "Deletion audit": "حسابرسی حذف",

    # Block Types
    "Text": "متن",
    "Regular Text": "متن عادی",
    "Heading": "سربرگ",
    "Subheading": "زیرسربرگ",
    "Title": "عنوان",
    "Paragraph": "پاراگراف",
    "Bullet list": "فهرست نشانه‌دار",
    "Numbered list": "فهرست شماره‌دار",
    "Toggle list": "فهرست کشویی",
    "Quote": "نقل‌قول",
    "Callout": "کادر پیام",
    "Code": "کد",
    "Inline Code": "کد درون‌خطی",
    "Divider": "خط جداکننده",
    "Table": "جدول",
    "Board": "برد",
    "Gallery": "نگارخانه",
    "Calendar": "گاه‌شمار",
    "List": "فهرست",
    "LaTeX": "لاتک (LaTeX)",
    "Mathematical formula": "فرمول ریاضی",
    "Mermaid": "مرمید (Mermaid)",
    "Diagram and flowchart": "نمودار و فلوچارت",

    # Dataview & Filters
    "View settings": "تنظیمات نما",
    "Column settings": "تنظیمات ستون",
    "Filter by Types": "پالایش بر اساس نوع‌ها",
    "Limit Object Types": "محدود کردن نوع‌های شیء",
    "Filter Object Types...": "پالایش نوع‌های شیء...",
    "Select Object Type": "انتخاب نوع شیء",
    "Add Object Type": "افزودن نوع شیء",
    "Type settings": "تنظیمات نوع",
    "Type name": "نام نوع",
    "Type plural name": "نام جمع نوع",
    "Editing type": "ویرایش نوع",
    "e.g. Project": "مثلاً پروژه",
    "e.g. Projects": "مثلاً پروژه‌ها",
    "Header": "سربرگ",
    "Properties panel": "پنل ویژگی‌ها",
    "Hidden": "پنهان",
    "Found in objects": "یافت‌شده در اشیاء",
    "There are no Properties yet": "هنوز ویژگی‌ای وجود ندارد",

    # Months
    "January": "ژانویه",
    "February": "فوریه",
    "March": "مارس",
    "April": "آوریل",
    "May": "مه",
    "June": "ژوئن",
    "July": "ژوئیه",
    "August": "اوت",
    "September": "سپتامبر",
    "October": "اکتبر",
    "November": "نوامبر",
    "December": "دسامبر",

    # Days
    "Monday": "دوشنبه",
    "Tuesday": "سه‌شنبه",
    "Wednesday": "چهارشنبه",
    "Thursday": "پنجشنبه",
    "Friday": "جمعه",
    "Saturday": "شنبه",
    "Sunday": "یکشنبه",
}

print(f"Phrase map contains {len(PHRASE_MAP)} entries.")
