# -*- coding: utf-8 -*-
"""
Direct Persian translations for the remaining phrases in Anytype.
Completes 100% of the untranslated keys.
"""

import sys
import json
import re

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

FA_FILE = 'dist/lib/json/lang/fa-IR.json'
EN_FILE = 'src/json/text.json'

with open(FA_FILE, 'r', encoding='utf-8') as f:
    fa = json.load(f)

with open(EN_FILE, 'r', encoding='utf-8') as f:
    en = json.load(f)

REMAINING_DICT = {
    "%d %s": "%d %s",
    "%d activities": "%d فعالیت",
    "%d failed": "%d ناموفق",
    "%s %s couldn't be synced.": "%s %s همگام‌سازی نشد.",
    "%s / %s": "%s / %s",
    "%s active in %s %s": "%s فعال در %s %s",
    "%s created %s": "%s، %s را ایجاد کرد",
    "%s created in %s %s": "%s در %s %s ایجاد شد",
    "%s edited %s": "%s، %s را ویرایش کرد",
    "%s edited in %s %s": "%s در %s %s ویرایش شد",
    "%s has been copied to clipboard": "%s در بریده‌دان کپی شد",
    "%s is a Collection now!": "%s اکنون یک مجموعه است!",
    "%s of %s": "%s از %s",
    "%s of %s loaded, %s stalled": "%s از %s بارگذاری شد، %s متوقف شد",
    "%s selected spaces are unavailable. Wait for them to appear, or remove them from this key.": "%s فضای انتخاب‌شده در دسترس نیستند. صبر کنید تا ظاهر شوند، یا آن‌ها را از این کلید حذف کنید.",
    "%s used": "%s استفاده شده",
    "%s/%s pages": "%s/%s برگه",
    "%s: %s": "%s: %s",
    "...": "...",
    "<b>Nothing found for <span>\"%s\"</span></b>Try a different search": "<b>چیزی برای <span>«%s»</span> یافت نشد</b>جستجوی دیگری را امتحان کنید",
    "<b>Sync to your mobile devices locally.</b> Scan the QR code to download the iOS or Android App and make use of peer-to-peer sync.": "<b>همگام‌سازی محلی با دستگاه‌های همراه.</b> کد QR را اسکن کنید تا برنامه iOS یا Android را دانلود کنید و از همگام‌سازی همتا به همتا بهره ببرید.",
    "<b>There are no Objects named <span>\"%s\"</span></b>Try to search for something else": "<b>هیچ شیئی به نام <span>«%s»</span> وجود ندارد</b>جستجوی مورد دیگری را امتحان کنید",
    "<b>There are no covers named <span>\"%s\"</span></b>Try to find a new one or upload your image": "<b>هیچ جلدی به نام <span>«%s»</span> وجود ندارد</b>جلد جدیدی پیدا کنید یا تصویر خود را بارگذاری کنید",
    "<b>View your network and peer-to-peer connection status here,</b> along with a list of synced objects.": "<b>وضعیت اتصال شبکه و همتا به همتا را در اینجا مشاهده کنید،</b> به همراه فهرستی از اشیاء همگام‌سازی‌شده.",
    "Access wasn’t approved. Check your selection and try again.": "دسترسی تأیید نشد. انتخاب خود را بررسی کنید و دوباره امتحان کنید.",
    "Add to the Type": "افزودن به نوع",
    "Animals & Nature": "حیوانات و طبیعت",
    "Any Network": "هر شبکه‌ای",
    "Anytype Identity": "شناسه Anytype",
    "An app wants to connect to your Anytype account": "یک برنامه می‌خواهد به حساب Anytype شما متصل شود",
    "Apps using API v1 need read and write access to all spaces.": "برنامه‌هایی که از API نسخه ۱ استفاده می‌کنند به دسترسی خواندن و نوشتن در تمام فضاها نیاز دارند.",
    "Back to dashboard": "بازگشت به پیشخوان",
    "Blue - Pink": "آبی - صورتی",
    "Build number": "شماره ساخت",
    "Channel Members": "اعضای کانال",
    "Channels help you organize your work and communicate with others.\nThey can be personal, one-to-one, or group — all in one place.": "کانال‌ها به شما کمک می‌کنند کار خود را سازماندهی کرده و با دیگران ارتباط برقرار کنید.\nآن‌ها می‌توانند شخصی، دونفره یا گروهی باشند — همگی در یک مکان.",
    "Clear style": "پاک کردن سبک",
    "Close sidebar": "بستن نوار کناری",
    "Congratulations! You can embed a Query or Collection and modify it using Filters and Views without altering the original instance.": "تبریک! می‌توانید یک پرس‌وجو یا مجموعه را جای‌گذاری کرده و با استفاده از فیلترها و نماها بدون تغییر نسخه اصلی، آن را تغییر دهید.",
    "Count checked": "تعداد علامت‌زده‌شده",
    "Count empty": "تعداد خالی",
    "Count unchecked": "تعداد علامت‌نزده",
    "Create from clipboard": "ایجاد از بریده‌دان",
    "Create your first channel": "اولین کانال خود را بسازید",
    "Create Your Perfect Channel": "کانال ایده‌آل خود را ایجاد کنید",
    "Data backup is disabled": "پشتیبان‌گیری از داده‌ها غیرفعال است",
    "Date created": "تاریخ ایجاد",
    "Date last used": "تاریخ آخرین استفاده",
    "Default template": "الگوی پیش‌فرض",
    "Default Type for this View": "نوع پیش‌فرض برای این نما",
    "Denying blocks this app until Anytype restarts.": "رد کردن دسترسی، این برنامه را تا راه‌اندازی مجدد Anytype مسدود می‌کند.",
    "Drafting your custom types...": "در حال تنظیم نوع‌های سفارشی شما...",
    "Drag'n'Drop": "بکشید و رها کنید",
    "End-to-end encrypted": "رمزگذاری سرتاسری",
    "Enter number": "وارد کردن عدد",
    "Error when uploading a file. Check if you have enough space and try again.": "خطا هنگام بارگذاری فایل. بررسی کنید که آیا فضای کافی دارید و دوباره امتحان کنید.",
    "Experience was successfully installed to the <b>'%s'</b> channel. You can now open and start using it.": "تجربه با موفقیت در کانال <b>«%s»</b> نصب شد. اکنون می‌توانید آن را باز کرده و استفاده کنید.",
    "Food & Drink": "غذا و نوشیدنی",
    "Good to have chat here now": "خوب شد که گفتگو به اینجا اضافه شد",
    "Help us to become better": "به ما در بهتر شدن کمک کنید",
    "Hello! I'm here to help you create your perfect channel. What project, idea, or challenge would you like to work on?": "سلام! من اینجا هستم تا به شما کمک کنم کانال ایده‌آل خود را ایجاد کنید. روی چه پروژه، ایده یا چالشی می‌خواهید کار کنید؟",
    "If you want to keep using this Object, change this Object Type.": "اگر می‌خواهید به استفاده از این شیء ادامه دهید، نوع این شیء را تغییر دهید.",
    "Incorrect E-mail": "ایمیل نادرست است",
    "Insert right": "درج در سمت راست",
    "It’s both a quick guide to Anytype and a sandbox where you can explore how Channels are organized. You can return to it whenever you like.": "این هم یک راهنمای سریع برای Anytype است و هم محیطی آزمایشی که در آن می‌توانید نحوه سازماندهی کانال‌ها را کشف کنید. هر زمان که مایل بودید می‌توانید به آن برگردید.",
    "It looks like the channel has been deleted. Please ensure that your devices are synchronized.": "به نظر می‌رسد این کانال حذف شده است. لطفاً اطمینان حاصل کنید که دستگاه‌های شما همگام هستند.",
    "It looks like the channel is no longer shared. Please ensure that your devices are synchronized.": "به نظر می‌رسد این کانال دیگر به اشتراک گذاشته نشده است. لطفاً اطمینان حاصل کنید که دستگاه‌های شما همگام هستند.",
    "Join Channel Button": "دکمه پیوستن به کانال",
    "Large heading": "سربرگ بزرگ",
    "Last opened Object": "آخرین شیء بازشده",
    "Limit reached for this channel. Please upgrade your membership or contact support for assistance.": "به سقف مجاز برای این کانال رسیده‌اید. لطفاً عضویت خود را ارتقا دهید یا با پشتیبانی تماس بگیرید.",
    "Load more replies": "بارگذاری پاسخ‌های بیشتر",
    "Local repo exists but is corrupted": "مخزن محلی وجود دارد اما آسیب دیده است",
    "Looks like some files are over %s. Please remove or slim them down and try again.": "به نظر می‌رسد برخی از فایل‌ها بیش از %s هستند. لطفاً آن‌ها را بردارید یا حجمشان را کم کنید و دوباره امتحان کنید.",
    "Manage Sections": "مدیریت بخش‌ها",
    "Name available": "نام در دسترس است",
    "Network error": "خطای شبکه",
    "No available actions": "عملیاتی در دسترس نیست",
    "No spaces available yet.": "هنوز فضایی در دسترس نیست.",
    "Now, let's take a look at the Properties menu.": "حالا بیایید نگاهی به منوی ویژگی‌ها بیندازیم.",
    "One Channel. Many Threads.": "یک کانال. رشته‌گفتگوهای متعدد.",
    "Only unlinked": "فقط بدون پیوند",
    "Oops! Something went wrong. Please try again later.": "اوه! مشکلی پیش آمد. لطفاً بعداً دوباره امتحان کنید.",
    "Oops! The request failed. Please check your Internet connection and try again.": "اوه! درخواست انجام نشد. لطفاً اتصال اینترنت خود را بررسی کرده و دوباره امتحان کنید.",
    "Percentage empty": "درصد خالی",
    "Private Channel": "کانال خصوصی",
    "Reach out people directly when you need a quick answer or a private channel to talk.": "هنگامی که به پاسخی سریع یا کانالی خصوصی برای گفتگو نیاز دارید، مستقیماً با افراد ارتباط برقرار کنید.",
    "Removal history": "تاریخچه حذف",
    "Same as in object view": "مشابه با نمای شیء",
    "Same as Object": "مشابه شیء",
    "See all Objects": "مشاهده همه اشیاء",
    "Select date": "انتخاب تاریخ",
    "Select files": "انتخاب فایل‌ها",
    "Select files...": "انتخاب فایل‌ها...",
    "Select one or more sources": "یک یا چند منبع را انتخاب کنید",
    "Select Property Type": "انتخاب نوع ویژگی",
    "Selection is empty": "چیزی انتخاب نشده است",
    "Show %s more %s": "نمایش %s مورد بیشتر از %s",
    "Show column": "نمایش ستون",
    "Sidebar View": "نمای نوار کناری",
    "Switch to detailed view": "تغییر به نمای با جزئیات",
    "Take our 1-minute survey to enhance collaboration. Your input makes Anytype better for everyone.": "در نظرسنجی ۱ دقیقه‌ای ما برای بهبود همکاری شرکت کنید. نظرات شما Anytype را برای همه بهتر می‌کند.",
    "Talk, and watch your chat growing": "گفتگو کنید و رشد چت خود را ببینید",
    "Tech information": "اطلاعات فنی",
    "Tell us how it's going!": "به ما بگویید اوضاع چطور پیش می‌رود!",
    "There are no Properties yet": "هنوز ویژگی‌ای وجود ندارد",
    "There are no values": "هیچ مقداری وجود ندارد",
    "These properties exist in some objects but aren't part of the Type. Add them to make them appear in all objects of this Type.": "این ویژگی‌ها در برخی اشیاء وجود دارند اما جزو این نوع نیستند. آن‌ها را اضافه کنید تا در تمام اشیاء این نوع ظاهر شوند.",
    "This Object": "این شیء",
    "This Object doesn't exist": "این شیء وجود ندارد",
    "This Template was set as default": "این الگو به عنوان پیش‌فرض تنظیم شد",
    "This type has %s %s": "این نوع دارای %s %s است",
    "This will permanently delete the channel. You can't undo this action. Please type the name of the channel to confirm deletion.": "این کار کانال را برای همیشه حذف می‌کند. این اقدام قابل بازگشت نیست. لطفاً نام کانال را برای تأیید حذف تایپ کنید.",
    "three years": "سه سال",
    "Travel & Places": "سفر و مکان‌ها",
    "Type it into %s to finish pairing.": "آن را در %s وارد کنید تا جفت‌سازی تکمیل شود.",
    "Unlinked Objects": "اشیاء بدون پیوند",
    "Update your profile, access your Key, and adjust app settings here.": "نمایه خود را به‌روزرسانی کنید، به کلید خود دسترسی داشته باشید و تنظیمات برنامه را در اینجا تغییر دهید.",
    "Upload a file": "بارگذاری فایل",
    "We don't have permission to import into this Anytype channel.": "ما مجوز درون‌ریزی به این کانال Anytype را نداریم.",
    "We'd love to learn more about why you've chosen to delete your vault. Would you be willing to take 3 minutes to help us improve?": "خیلی دوست داریم بدانیم چرا تصمیم به حذف مخزن امن خود گرفته‌اید. آیا مایلید ۳ دقیقه برای کمک به بهبود ما وقت بگذارید؟",
    "Widget <b>%s</b> has been added": "ابزارک <b>«%s»</b> اضافه شد",
    "Widget with a compact list view": "ابزارک با نمای فهرست فشرده",
    "Widget with a list view": "ابزارک با نمای فهرست",
    "Wonderful selection! Building your channel now...": "انتخاب عالی! در حال ساخت کانال شما...",
    "Write a reply...": "نوشتن پاسخ...",
    "You can find the imported objects in the selected channel.": "می‌توانید اشیاء درون‌ریزی‌شده را در کانال انتخاب‌شده بیابید.",
    "You can only delete objects you created": "شما فقط می‌توانید اشیایی را که خودتان ایجاد کرده‌اید حذف کنید",
    "Your files were imported with %s %s. See the report for details.": "فایل‌های شما با %s %s درون‌ریزی شدند. برای جزئیات به گزارش مراجعه کنید.",
    "Your local storage exceeds syncing limit. Locally stored files won't be synced": "حافظه محلی شما از حد مجاز همگام‌سازی فراتر رفته است. فایل‌های ذخیره‌شده محلی همگام‌سازی نخواهند شد",
    "Your request to join the <b>'%s'</b> channel has been declined.": "درخواست شما برای پیوستن به کانال <b>«%s»</b> رد شده است.",
    "Your Vault is currently in local-only mode, so your data isn't being synced to Anytype nodes.": "مخزن امن شما در حال حاضر در حالت فقط-محلی است، بنابراین داده‌های شما با نودهای Anytype همگام‌سازی نمی‌شوند.",
    "Group chats by projects, teams, or topics using tags and properties — just like you organize your knowledge": "چات‌های گروهی را بر اساس پروژه‌ها، تیم‌ها یا موضوعات با استفاده از برچسب‌ها و ویژگی‌ها گروه‌بندی کنید — درست مانند سازماندهی دانش خود",
    "Everything You Talk About": "همه آنچه درباره‌اش گفتگو می‌کنید",
    "Each object has a Type. Think of it as a super-tag that keeps things organized: Pages, Tasks, or any custom type you create. New objects automatically land in their category here.": "هر شیء یک نوع دارد. آن را مانند یک ابربرچسب تصور کنید که موارد را منظم نگه می‌دارد: برگه‌ها، کارها یا هر نوع سفارشی که بسازید. اشیاء جدید به‌طور خودکار در دسته‌بندی مربوطه قرار می‌گیرند.",
    "Import failed": "درون‌ریزی ناموفق بود",
    "No, don't use it": "خیر، استفاده نشود",
    "Since Anytype stores all your data locally on the device, you need to remove it from other devices also. Launch and remove data in Anytype or just delete the app.": "از آنجا که Anytype تمام داده‌های شما را به‌صورت محلی روی دستگاه ذخیره می‌کند، باید آن را از سایر دستگاه‌ها نیز حذف کنید. Anytype را اجرا کرده و داده‌ها را پاک کنید یا به سادگی برنامه را حذف نمایید.",
    "Use the first row as column names": "استفاده از سطر اول به عنوان نام ستون‌ها",
    "All <b>@mentions</b> will be converted to text": "تمام <b>@اشاره‌ها</b> به متن تبدیل خواهند شد",
    "Paste your personal access token": "توکن دسترسی شخصی خود را جای‌گذاری کنید",
    "Give the token a name. Under <b>Capabilities</b> you can leave only <b>Notion API</b> enabled.": "یک نام برای توکن بگذارید. در بخش <b>قابلیت‌ها</b> فقط می‌توانید <b>Notion API</b> را فعال نگه دارید.",
    "Click <b>Create token</b> and copy it. The token starts with <b>ntn_</b>. Paste it in the field above.": "روی <b>ساخت توکن</b> کلیک کرده و آن را کپی کنید. توکن با <b>ntn_</b> شروع می‌شود. آن را در کادر بالا جای‌گذاری نمایید.",
    "Import your Obsidian files with 3 simple steps": "درون‌ریزی فایل‌های Obsidian با ۳ گام ساده",
    "<ul><li>Open the Vault switcher (shown at launch or via File → Open Vault).</li><li>Right-click the vault you want to export and choose “Reveal in system explorer”.</li></ul>": "<ul><li>انتخاب‌گر مخزن را باز کنید (در هنگام اجرا یا از طریق پرونده ← باز کردن مخزن).</li><li>روی مخزنی که می‌خواهید برون‌بری کنید راست‌کلیک کرده و گزینه «نمایش در کاوشگر سیستم» را برگزینید.</li></ul>",
    "<ul><li>[[Internal Links]] → become linked objects in Anytype, so the connections between your notes are preserved.</li><li>Frontmatter (the --- metadata at the top) → becomes object properties.</li></ul>": "<ul><li>[[پیوندهای درونی]] ← تبدیل به اشیاء متصل در Anytype می‌شوند تا ارتباط یادداشت‌های شما حفظ شود.</li><li>فراداده‌های سربرگ (علامت‌های --- در بالا) ← تبدیل به ویژگی‌های شیء می‌شوند.</li></ul>",
    "Organize with AI": "سازماندهی با هوش مصنوعی",
    "Decisions made by the model are listed on the import report.": "تصمیمات گرفته‌شده توسط مدل در گزارش درون‌ریزی ثبت می‌شوند.",
    "Runs on this device. Your data never leaves your machine.": "روی همین دستگاه اجرا می‌شود. داده‌های شما هرگز دستگاهتان را ترک نمی‌کنند.",
    "Make sure you saved your login key": "اطمینان حاصل کنید که کلید ورود خود را ذخیره کرده‌اید",
    "Exit AI Onboarding?": "خروج از راه‌اندازی با هوش مصنوعی؟",
    "Are you sure you want to exit? Your progress will be lost.": "آیا مطمئن هستید که می‌خواهید خارج شوید؟ پیشرفت شما از دست خواهد رفت.",
    "Something went wrong. Please try again.": "مشکلی پیش آمد. لطفاً دوباره تلاش کنید.",
    "Join by invite link": "پیوستن از طریق پیوند دعوت",
    "Name is too short": "نام بسیار کوتاه است",
    "Enter the code you received after purchase or from invatation. Your membership will be activated instantly.": "کدی را که پس از خرید یا از دعوت‌نامه دریافت کرده‌اید وارد کنید. عضویت شما بلافاصله فعال خواهد شد.",
    "Paste activation code...": "جای‌گذاری کد فعال‌سازی...",
    "Unknown error occured": "خطای ناشناخته رخ داد",
    "You are on the latest version: %s": "شما از آخرین نسخه استفاده می‌کنید: %s",
    "There was a problem while opening the object, please send the debug info to the support team.": "مشکلی هنگام باز کردن شیء پیش آمد، لطفاً اطلاعات عیب‌یابی را برای تیم پشتیبانی ارسال فرمایید.",
    "Collect debug info": "جمع‌آوری اطلاعات عیب‌یابی",
    "Remove the member from this channel?": "آیا این عضو از کانال حذف شود؟",
    "The current link stops working for everyone who has it, including the people you meant to invite. A new link is created in its place.": "پیوند فعلی برای همه کسانی که آن را دارند از کار خواهد افتاد. یک پیوند جدید جایگزین آن می‌شود.",
    "Show me what I can build": "به من نشان بده چه چیزی می‌توانم بسازم",
    "Explore membership options for more storage, extra channel editors, and additional channels. Pick the option that works best for you.": "گزینه‌های عضویت را برای حافظه بیشتر، ویرایشگران بیشتر و کانال‌های اضافه بررسی کنید. گزینه‌ای را که برایتان مناسب‌تر است برگزینید.",
    "Report generated": "گزارش ایجاد شد",
    "Share the archive with support@anytype.io and describe your issue.<br/><br/>The report includes recent error logs, object and channel IDs, your public identity ID, and basic device info (OS, processor, etc). It does not include object content. Feel free to review the archive before sending.": "فایل فشرده را با support@anytype.io به اشتراک بگذارید و مشکل خود را شرح دهید.<br/><br/>این گزارش شامل لاگ‌های خطای اخیر، شناسه‌های شیء و کانال و اطلاعات پایه دستگاه است و محتوای اشیاء را شامل نمی‌شود.",
    "You are trying to open an url that is potentially harmful. Are you sure you want to proceed?<br/>Url: %s": "شما در حال باز کردن نشانی اینترنتی بالقوه خطرناک هستید. آیا مطمئن هستید که می‌خواهید ادامه دهید؟<br/>نشانی: %s",
    "It cannot be restored after confirmation": "پس از تأیید امکان بازیابی وجود نخواهد داشت",
    "These Properties will be added to the Type and will appear in all objects of this specific Type.": "این ویژگی‌ها به این نوع اضافه شده و در تمام اشیاء این نوع پدیدار خواهند شد.",
    "This will reset layout type, alignment, and featured properties for all objects of this type. This action cannot be undone.<br/>Are you sure?": "این کار نوع چیدمان، تراز و ویژگی‌های برجسته تمام اشیاء این نوع را بازنشانی می‌کند. این عمل غیرقابل‌بازگشت است.<br/>آیا مطمئن هستید؟",
    "Looks like your device is almost out of space. This might cause the app to misbehave or lose your changes. Try clearing up some storage to keep everything running smoothly.": "به نظر می‌رسد فضای دستگاه شما رو به اتمام است. لطفاً برای کارکرد روان برنامه مقداری فضا آزاد کنید.",
    "Delete Object Type?": "حذف نوع شیء؟",
    "Your upgrade means a lot to us. Tell us what made you take the step and what do you think about Anytype. A tiny survey from you = a huge boost for us.": "ارتقای شما ارزش بالایی برای ما دارد. به ما بگویید چه چیزی شما را به این گام ترغیب کرد و درباره Anytype چه فکر می‌کنید.",
    "Move “%s” to Bin?": "انتقال «%s» به زباله‌دان؟",
    "Move %s types to Bin?": "انتقال %s نوع به زباله‌دان؟",
    "This channel requires owner approval. Send a request and you'll be notified once it's approved.": "این کانال نیاز به تأیید مالک دارد. درخواستی ارسال کنید تا پس از تأیید به شما اطلاع داده شود.",
    "✦ Add more editors": "✦ افزودن ویرایشگران بیشتر",
    "This invite is shared with the channel, so it can only grant viewer access.": "این دعوت با کانال به اشتراک گذاشته شده، بنابراین فقط دسترسی بیننده می‌دهد.",
    "Share this invite with the channel?": "اشتراک‌گذاری این دعوت با کانال؟",
    "All channel members will be able to see this invite link and share it with anyone. To make it private again, you'll need to reset the link.": "تمام اعضای کانال می‌توانند این پیوند دعوت را ببینند و آن را به اشتراک بگذارند.",
    "Review your invite link": "بررسی پیوند دعوت شما",
    "This channel's invitation link grants Editor access without approval, and everyone in the channel can see it — including Viewers, who can use it to upgrade themselves to Editor. Review the link and reset it if this is not what you intend.": "پیوند دعوت این کانال دسترسی ویرایشگر بدون نیاز به تأیید می‌دهد. اگر این مد نظر شما نیست، پیوند را بازنشانی کنید.",
    "Anyone with this link joins as an editor without approval, and everyone in the channel can see it — including viewers. Reset the link to make a safe one.": "هر کسی با این پیوند بدون تأیید به عنوان ویرایشگر وارد می‌شود. برای امن کردن، پیوند را بازنشانی کنید.",
    "Search for an object · / to filter...": "جستجوی یک شیء · / برای فیلتر...",
    "Search %s in all Channels": "جستجوی %s در تمام کانال‌ها",
    "Include files data": "شامل داده‌های فایل‌ها",
    "The export was canceled. Any files already written may be incomplete.": "برون‌بری لغو شد. فایل‌های نوشته‌شده ممکن است ناقص باشند.",
    "Open export folder": "باز کردن پوشه برون‌بری",
    "Click any shortcut to edit it": "روی هر میانبر کلیک کنید تا آن را ویرایش نمایید",
    "Reset All To Default": "بازنشانی همه به پیش‌فرض",
    "Your current shortcut mapping will be reset to default.": "میانبرهای فعلی شما به حالت پیش‌فرض بازنشانی می‌شوند.",
    "Shortcuts mapping updated": "نگاشت میانبرها به‌روزرسانی شد",
    "Select block and all blocks in between": "انتخاب بلوک و تمام بلوک‌های بین آن‌ها",
    "Duplicate selected blocks": "تکثیر بلوک‌های انتخاب‌شده",
    "Open the Graph pane": "باز کردن پنل گراف",
    "Open search from anywhere": "باز کردن جستجو از هر کجا",
    "One search for everything. Narrow it down by type, person or Channel": "یک جستجو برای همه‌چیز. با نوع، شخص یا کانال فیلتر کنید",
    "Press any key to start searching": "هر کلیدی را برای شروع جستجو فشار دهید",
    "This shortcut is used by another application": "این میانبر توسط برنامه دیگری استفاده می‌شود",
    "Turn block into a toggle": "تبدیل بلوک به فهرست کشویی",
    "Go to the previous option": "رفتن به گزینه قبلی",
    "Go to the start of the line": "رفتن به ابتدای خط",
    "Go to the top of the Object": "رفتن به بالای شیء",
    "Move selected block(s) up": "انتقال بلوک(های) انتخاب‌شده به بالا",
    "Create a toggle H1 heading": "ایجاد سربرگ H1 کشویی",
    "Create an Object with a relative date": "ایجاد شیء با تاریخ نسبی",
    "It's your login and password": "این نام کاربری و گذرواژه شماست",
    "Your key is represented by a recovery phrase — 12 random words that generate your vault on this device.": "کلید شما با یک عبارت بازیابی نمایش داده می‌شود — ۱۲ کلمه تصادفی که مخزن امن شما را روی این دستگاه تولید می‌کند.",
    "Anyone who knows these words can access your vault. Right now, you are the only person in the world who knows them.": "هر کسی این کلمات را بداند به مخزن شما دسترسی خواهد داشت. اکنون شما تنها کسی در جهان هستید که آن‌ها را می‌داند.",
    "All computational resources on Earth are not enough to break in. If you lose your key, it cannot be recovered. Store it somewhere safe — in a password manager or written down on paper.": "اگر کلید خود را گم کنید، قابل بازیابی نیست. آن را در جایی امن ذخیره کنید — در یک نرم‌افزار مدیریت رمز عبور یا یادداشت‌شده روی کاغذ.",
    "There are no Properties shown yet": "هنوز ویژگی‌ای نمایش داده نشده است",
    "There are no items": "هیچ موردی وجود ندارد",
    "Paste a file URL": "نشانی اینترنتی فایل را جای‌گذاری کنید",
    "Turn into divider": "تبدیل به خط جداکننده",
    "Include page content": "شامل محتوای برگه",
    "Error parsing URL": "خطا در پردازش نشانی اینترنتی",
    "Installed from Gallery": "نصب‌شده از نگارخانه",
    "RemoteWaitingDeletion": "در انتظار حذف از راه دور",
    "Perfect! A few quick questions:": "عالی! چند سؤال کوتاه:"
}

# Update translations
applied = 0
for k, v in en.items():
    if v in REMAINING_DICT:
        fa[k] = REMAINING_DICT[v]
        applied += 1
    elif k in REMAINING_DICT:
        fa[k] = REMAINING_DICT[k]
        applied += 1

print(f"Applied {applied} translations from REMAINING_DICT.")

# Ensure system keys are preserved exactly
EXACT_ENFORCE = {
    "popupSettingsPersonalLayoutDirection": "چیدمان",
    "popupSettingsPersonalLayoutRtl": "از راست به چپ",
    "popupSettingsPersonalLayoutLtr": "از چپ به راست",
    "commonTypePage": "برگه",
    "commonTypePages": "برگه‌ها",
    "commonTypeTask": "کار",
    "commonTypeTasks": "کارها",
    "commonTypeCollection": "مجموعه",
    "commonTypeCollections": "مجموعه‌ها",
    "commonTypeBookmark": "نشانک",
    "commonTypeBookmarks": "نشانک‌ها",
    "commonTypeImage": "تصویر",
    "commonTypeImages": "تصاویر",
    "commonTypeNote": "یادداشت",
    "commonTypeNotes": "یادداشت‌ها",
    "commonTypeFile": "فایل",
    "commonTypeFiles": "فایل‌ها",
    "commonTypeVideo": "ویدیو",
    "commonTypeVideos": "ویدیوها",
    "commonTypeAudio": "صدا",
    "commonTypeAudios": "صداها",
    "commonShare": "اشتراک‌گذاری",
    "headerShare": "اشتراک‌گذاری",
    "commonSettings": "تنظیمات",
    "commonDescription": "توضیحات",
    "editorControlDescription0": "نمایش توضیحات",
    "editorControlDescription1": "پنهان کردن توضیحات",
    "editorControlCover0": "افزودن جلد",
    "editorControlCover1": "تغییر جلد",
    "editorControlIcon0": "افزودن آیکون",
    "editorControlLayout": "تنظیمات",
    "widgetSection0": "صفحه اصلی و سنجاق‌شده",
    "widgetSection1": "نوع‌ها",
    "widgetSection2": "خوانده‌نشده",
    "widgetSection3": "اخیراً ویرایش‌شده",
    "widgetSection4": "زباله‌دان",
    "widgetSection5": "علاقه‌مندی‌های من",
    "widgetSection6": "درختواره",
}

for k, v in EXACT_ENFORCE.items():
    fa[k] = v

with open(FA_FILE, 'w', encoding='utf-8') as f:
    json.dump(fa, f, ensure_ascii=False, indent=4)

print("Saved updated fa-IR.json successfully!")
